using System;
using System.Drawing;

namespace RE2REmakeSRT
{
    public enum ItemEnumeration : int
    {
        None = 0,
        FirstAidSpray = 0x01,
        Herb_Green1 = 0x02,
        Herb_Red1 = 0x03,
        Herb_Blue1 = 0x04,
        Herb_Mixed_GG = 0x05,
        Herb_Mixed_GR = 0x06,
        Herb_Mixed_GB = 0x07,
        Herb_Mixed_GGB = 0x08,
        Herb_Mixed_GGG = 0x09,
        Herb_Mixed_GRB = 0x0A,
        Herb_Mixed_RB = 0x0B,
        Herb_Green2 = 0x0C, // ???
        Herb_Red2 = 0x0D, // ???
        Herb_Blue2 = 0x0E, // ???
        HandgunBullets = 0x0F,
        ShotgunShells = 0x10,
        SubmachineGunAmmo = 0x11,
        MAGAmmo = 0x12,
        GrenadeAcidRounds = 0x16,
        GrenadeFlameRounds = 0x17,
        NeedleCartridges = 0x18,
        Fuel = 0x19,
        HandgunLargeCaliberAmmo = 0x1A,
        SLS60HighPoweredRounds = 0x1B,
        Detonator = 0x1F,
        InkRibbon = 0x20,
        WoodenBoard = 0x21,
        ElectronicGadget = 0x22,
        Battery9Volt = 0x23,
        Gunpowder = 0x24,
        GunpowderLarge = 0x25,
        GunpowderHighGradeYellow = 0x26,
        GunpowderHighGradeWhite = 0x27,
        MatildaHighCapacityMagazine = 0x30,
        MatildaMuzzleBrake = 0x31,
        MatildaGunStock = 0x32,
        SLS60SpeedLoader = 0x33,
        JMBHp3LaserSight = 0x34,
        SLS60ReinforcedFrame = 0x35,
        JMBHp3HighCapacityMagazine = 0x36,
        W870ShotgunStock = 0x37,
        W870LongBarrel = 0x38,
        MQ11HighCapacityMagazine = 0x3A,
        MQ11Suppressor = 0x3C,
        LightningHawkRedDotSight = 0x3D,
        LightningHawkLongBarrel = 0x3E,
        GM79ShoulderStock = 0x40,
        FlamethrowerRegulator = 0x41,
        SparkShotHighVoltageCondenser = 0x42,
        Film_HidingPlace = 0x48,
        Film_RisingRookie = 0x49,
        Film_Commemorative = 0x4A,
        Film_3FLocker = 0x4B,
        Film_LionStatue = 0x4C,
        KeyStorageRoom = 0x4D,
        JackHandle = 0x4F,
        SquareCrank = 0x50,
        MedallionUnicorn = 0x51,
        KeySpade = 0x52,
        KeyCardParkingGarage = 0x53,
        KeyCardWeaponsLocker = 0x54,
        ValveHandle = 0x56,
        STARSBadge = 0x57,
        Scepter = 0x58,
        RedJewel = 0x5A,
        BejeweledBox = 0x5B,
        PlugBishop = 0x5D,
        PlugRook = 0x5E,
        PlugKing = 0x5F,
        PictureBlock = 0x62,
        USBDongleKey = 0x66,
        SpareKey = 0x70,
        RedBook = 0x72,
        StatuesLeftArm = 0x73,
        StatuesLeftArmWithRedBook = 0x74,
        MedallionLion = 0x76,
        KeyDiamond = 0x77,
        KeyCar = 0x78,
        MedallionMaiden = 0x7C,
        PowerPanelPart1 = 0x7E,
        PowerPanelPart2 = 0x7F,
        LoversRelief = 0x80,
        GearSmall = 0x81,
        GearLarge = 0x82,
        KeyCourtyard = 0x83,
        PlugKnight = 0x84,
        PlugPawn = 0x85,
        PlugQueen = 0x86,
        BoxedElectronicPart1 = 0x87,
        BoxedElectronicPart2 = 0x88,
        KeyOrphanage = 0x9F,
        KeyClub = 0xA0,
        KeyHeart = 0xA9,
        USSDigitalVideoCassette = 0xAA,
        TBarValveHandle = 0xB0,
        DispersalCartridgeEmpty = 0xB3,
        DispersalCartridgeSolution = 0xB4,
        DispersalCartridgeHerbicide = 0xB5,
        JointPlug = 0xB7,
        UpgradeChipAdministrator = 0xBA,
        IDWristbandAdministrator = 0xBB,
        ElectronicChip = 0xBC,
        SignalModulator = 0xBD,
        Trophy1 = 0xBE,
        Trophy2 = 0xBF,
        KeySewers = 0xC2,
        IDWristbandVisitor1 = 0xC3,
        IDWristbandGeneralStaff1 = 0xC4,
        IDWristbandSeniorStaff1 = 0xC5,
        UpgradeChipGeneralStaff = 0xC6,
        UpgradeChipSeniorStaff = 0xC7,
        IDWristbandVisitor2 = 0xC8,
        IDWristbandGeneralStaff2 = 0xC9,
        IDWristbandSeniorStaff2 = 0xCA,
        LabDigitalVideoCassette = 0xCB,
        Briefcase = 0xE6,
        FuseMainHall = 0xF0,
        FuseBreakRoom = 0xF1,
        Scissors = 0xF3,
        BoltCutter = 0xF4,
        StuffedDoll = 0xF5,
        HipPouch = 0x0106,
        PortableSafe = 0x0123,
        TinStorageBox1 = 0x0125,
        WoodenBox1 = 0x0126,
        WoodenBox2 = 0x0127,
        TinStorageBox2 = 0x0128,

        // Added because these images exist but the item ids do not?
        JointPlug2 = 0x7F000001,
        GearLarge2 = 0x7F000002,
    }

    public enum WeaponEnumeration : int
    {
        None = -1,
        Handgun_Matilda = 0x01,
        Handgun_M19 = 0x02,
        Handgun_JMB_Hp3 = 0x03,
        Handgun_Quickdraw_Army = 0x04, // Colt SAA
        Handgun_MUP = 0x07,
        Handgun_BroomHc = 0x08,
        Handgun_SLS60 = 0x09,
        Shotgun_W870 = 0x0B,
        SMG_MQ11 = 0x15,
        SMG_LE5_Infinite = 0x17,
        Handgun_LightningHawk = 0x1F,
        EMF_Visualizer = 0x29,
        GrenadeLauncher_GM79 = 0x2A,
        ChemicalFlamethrower = 0x2B,
        SparkShot = 0x2C,
        ATM4 = 0x2D,
        CombatKnife = 0x2E,
        CombatKnife_Infinite = 0x2F,
        AntiTankRocketLauncher = 0x31,
        Minigun = 0x32,
        HandGrenade = 0x41,
        FlashGrenade = 0x42,
        Handgun_SamuraiEdge_Infinite = 0x52,
        Handgun_SamuraiEdge_ChrisRedfield = 0x53,
        Handgun_SamuraiEdge_JillValentine = 0x54,
        Handgun_SamuraiEdge_AlbertWesker = 0x55,
        ATM4_Infinite = 0xDE,
        AntiTankRocketLauncher_Infinite = 0xF2,
        Minigun_Infinite = 0xFC,

        // Added because these images exist but the item ids do not?
        ChemicalFlamethrower2 = 0x7F000001,
        SparkShot2 = 0x7F000002,
        ATM42 = 0x7F000003,
        ATM43 = 0x7F000004,
        ATM44 = 0x7F000005,
        AntiTankRocketLauncher2 = 0x7F000006,
        AntiTankRocketLauncher3 = 0x7F000007,
        AntiTankRocketLauncher4 = 0x7F000008,
        Minigun2 = 0x7F000009,
        Minigun3 = 0x7F00000A,
        Minigun4 = 0x7F00000B,
        SMG_LE5_Infinite2 = 0x7F00000C,
    }

    [Flags]
    public enum AttachmentsFlag : int
    {
        None = 0x00,
        First = 0x01, // Weapons that never occupy two-slots will not have this flag for attachments.
        Second = 0x02,
        Third = 0x04
    }

    public struct Weapon : IEquatable<Weapon>
    {
        public WeaponEnumeration WeaponID;
        public AttachmentsFlag Attachments;

        public bool Equals(Weapon other) => (int)this.WeaponID == (int)other.WeaponID && (int)this.Attachments == (int)other.Attachments;
    }
}
